decrypt:
  ghpat.txt: "repo/ghpat.txt.asc"
release:
  script: |
    repo=Yegorov/test-rultor
    # read -r -s ghpat < ../ghpat.txt
    # git remote set-url origin https://${ghpat}@github.com/${repo}.git
    git show-branch origin/gh-pages
    if git show-branch origin/gh-pages; then
      git checkout gh-pages
    else
      git checkout --orphan gh-pages
    fi
    # git pull origin gh-pages
    rm -rf *
    git rm -rf *
    git checkout master -- md/*.md
    git checkout master -- README.md
    cp md/*.md .
    rm -rf md
    sha384sum *.md > checksums.txt
    git add .
    git commit -m "version set to ${tag}"
    # git push origin gh-pages
