release:
  script: |-
    flags=''
    [[ -z "$(git branch -r | grep 'origin/gh-pages')" ]] && flags+='--orphan'
    git checkout ${flags} gh-pages
    rm -rf *
    git rm -rf *
    git checkout master -- md/*.md
    git checkout master -- README.md
    cp md/*.md .
    rm -rf md
    sha384sum *.md > checksums.txt
    git add .
    git commit --allow-empty -m "version set to ${tag}"
