release:
  script: |-
    if git show-branch origin/gh-pages; then
      git checkout gh-pages
    else
      git checkout --orphan gh-pages
    fi
    rm -rf *
    git rm -rf *
    git checkout master -- md/*.md
    git checkout master -- README.md
    cp md/*.md .
    rm -rf md
    sha384sum *.md > checksums.txt
    git add .
    git commit -m "version set to ${tag}"
