release:
  script: |-
    flags=''
    git show-branch origin/gh-pages
    [[ $? -ne 0 ]] && flags+='--orphan'
    git checkout ${flags} gh-pages
    rm -rf *
    git rm -rf *
    git checkout master -- md/*.md
    git checkout master -- README.md
    cp md/*.md .
    rm -rf md
    sha384sum *.md > checksums.txt
    git add .
    git commit -m "version set to ${tag}"
